import { ArrowRight, Download, FileClock, MoreVertical } from 'lucide-react';
import Card from '@/Components/Shared/Card';
import IconButton from '@/Components/Shared/IconButton';
import { cn } from '@/utils/helpers';
import PanelTitle from './PanelTitle';

const FORMAT_TONES = {
    PDF: 'bg-danger-soft text-danger',
    XLSX: 'bg-success-soft text-success',
    CSV: 'bg-brand-soft text-brand',
};

export default function GeneratedReportsTable({ reports = [], onDownload, onViewAll }) {
    return (
        <Card
            title={<PanelTitle icon={FileClock}>Generated Reports</PanelTitle>}
            className="flex h-full flex-col"
        >
            <div className="table-wrap flex-1">
                <table className="data-table">
                    <thead>
                        <tr>
                            <th>Report Name</th>
                            <th>Date Range</th>
                            <th>Generated By</th>
                            <th>Generated On</th>
                            <th>Format</th>
                            <th className="text-right">Action</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                        {reports.map((report) => (
                            <tr key={report.id}>
                                <td className="font-medium text-slate-900">{report.name}</td>
                                <td className="text-slate-500">{report.range}</td>
                                <td className="text-slate-500">{report.generated_by}</td>
                                <td className="text-slate-500">{report.generated_on}</td>
                                <td>
                                    <span
                                        className={cn(
                                            'badge',
                                            FORMAT_TONES[report.format] || 'bg-slate-100 text-slate-600',
                                        )}
                                    >
                                        {report.format}
                                    </span>
                                </td>
                                <td>
                                    <div className="flex items-center justify-end gap-1">
                                        <IconButton
                                            label={`Download ${report.name}`}
                                            className="h-7 w-7"
                                            onClick={() => onDownload?.(report)}
                                        >
                                            <Download className="h-4 w-4" />
                                        </IconButton>
                                        <IconButton
                                            label={`Options for ${report.name}`}
                                            className="h-7 w-7"
                                        >
                                            <MoreVertical className="h-4 w-4" />
                                        </IconButton>
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            <button
                type="button"
                onClick={onViewAll}
                className="mt-3 inline-flex items-center gap-1 self-start text-xs font-medium text-brand hover:underline"
            >
                View all generated reports
                <ArrowRight className="h-3 w-3" />
            </button>
        </Card>
    );
}
